<!--FOOTER-->
    <!-- jQuery -->
    <script src="bootstrap/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="bootstrap/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="bootstrap/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="bootstrap/vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="bootstrap/vendors/Chart.js/dist/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="bootstrap/vendors/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="bootstrap/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="bootstrap/vendors/iCheck/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="bootstrap/vendors/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="bootstrap/vendors/Flot/jquery.flot.js"></script>
    <script src="bootstrap/vendors/Flot/jquery.flot.pie.js"></script>
    <script src="bootstrap/vendors/Flot/jquery.flot.time.js"></script>
    <script src="bootstrap/vendors/Flot/jquery.flot.stack.js"></script>
    <script src="bootstrap/vendors/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="bootstrap/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="bootstrap/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="bootstrap/vendors/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="bootstrap/vendors/DateJS/build/date.js"></script>
    <!-- JQVMap -->
    <script src="bootstrap/vendors/jqvmap/dist/jquery.vmap.js"></script>
    <script src="bootstrap/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
    <script src="bootstrap/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="bootstrap/vendors/moment/min/moment.min.js"></script>
    <script src="boottrap/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="bootstrap/build/js/custom.min.js"></script>
	
  </body>
</html>
